services:
  jenkins:
    image: jenkins/jenkins:lts-alpine 
    networks:
      - jenkins-sonar
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
  sonarqube:
    image: sonarqube
    networks:
      - jenkins-sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
networks:
  jenkins-sonar:
volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: